version: "3.9"

services:
  front_javascript_vue:
    build: .
    container_name: front_javascript_vue
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev